package common

const (
	//API GENERIC ERROR CODE
	REQUIRED_FIELD_CRITERIA_NOT_MATCHING_CODE = 1000
	RESPONSE_UNMARSHAL_EXCEPTION_CODE         = 1001
	REQUEST_MARSHAL_EXCEPTION_CODE            = 1002
	REQUEST_VALIDATION_EXCPETION_CODE         = 1003
	REQUEST_GENERATION_EXCEPTION_CODE         = 1004
	REQUEST_FAILED_CODE                       = 1005
	RESPONSE_ERROR_CODE                       = 1006
	RESPONSE_IO_ERROR_CODE                    = 1007
)

const (
	//API GENERIC ERROR INFO
	REQUIRED_FIELD_CRITERIA_NOT_MATCHING_INFO = "REQUIRED_FIELD_CRITERIA_NOT_MATCHING"
	RESPONSE_UNMARSHAL_EXCEPTION_INFO         = "RESPONSE_UNMARSHAL_EXCEPTION"
	REQUEST_MARSHAL_EXCEPTION_INFO            = "RESPONSE_MARSHAL_EXCEPTION"
	REQUEST_VALIDATION_EXCPETION_INFO         = "REQUEST_VALIDATION_EXCPETION"
	REQUEST_GENERATION_EXCEPTION_INFO         = "REQUEST_GENERATION_EXCEPTION"
	REQUEST_FAILED_INFO                       = "REQUEST_FAILED"
	RESPONSE_ERROR_INFO                       = "RESPONSE_ERROR"
	RESPONSE_IO_ERROR_INFO                    = "RESPONSE_IO_ERROR"
)
